name: Build

on: [push]
jobs:
  build:    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "pypy3.10"]
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Rye
        uses: eifinger/setup-rye@v3
        with:
          version: 'latest'
      
      - name: Install dependencies
        run: |
          rye install
          rye install --dev
      
      - name: lint 
        run: |
          make lint 
      
      - name: test
        run: |
          make test

